export type RiskLevel = 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
export type RiskFactor = { code: string; category: 'tool' | 'environment' | 'authorization' | 'grant' | 'approval' | 'egress' | 'agent'; labelKey: string; descriptionKey: string; scoreDelta: number; severity: RiskLevel; evidence?: Record<string, string | number | boolean> };
export type RiskInput = { method: string; tags: string[]; url: string; policyDecision: 'ALLOW' | 'DENY' | 'REQUIRE_APPROVAL'; defaultDecisionUsed: boolean; grantRequired: boolean; grantAllowed: boolean; grantExecutionCount?: number; grantMaxExecutions?: number; grantExpiresAt?: Date; agentEnabled: boolean; agentEnvironment?: string | null };
export type RiskResult = { score: number; level: RiskLevel; factors: RiskFactor[]; evaluatedAt: string; riskModelVersion: 'v1' };
const severity = (delta: number): RiskLevel => delta >= 20 ? 'HIGH' : delta >= 10 ? 'MEDIUM' : 'LOW';
export const riskLevel = (score: number): RiskLevel => score >= 75 ? 'CRITICAL' : score >= 50 ? 'HIGH' : score >= 25 ? 'MEDIUM' : 'LOW';
export function evaluateRisk(input: RiskInput, evaluatedAt: Date): RiskResult {
  const factors: RiskFactor[] = []; const add = (code: string, category: RiskFactor['category'], scoreDelta: number, evidence?: RiskFactor['evidence']) => factors.push({ code, category, scoreDelta, severity: severity(Math.abs(scoreDelta)), labelKey: `risk.factor.${code}.label`, descriptionKey: `risk.factor.${code}.description`, evidence });
  const method = input.method.toUpperCase(); if (method === 'DELETE') add('DESTRUCTIVE_METHOD', 'tool', 20, { method }); else if (['POST','PUT','PATCH'].includes(method)) add('WRITE_METHOD','tool',12,{method}); else if (method === 'GET') add('READ_METHOD','tool',-5,{method});
  const tags = new Set(input.tags.map((tag) => tag.toLowerCase().replace(/_/g,'-'))); const weighted: Array<[string,number]> = [['destructive',20],['privileged',18],['admin',15],['financial',15],['personal-data',12],['external',8],['production',12],['read-only',-8]]; for (const [tag,delta] of weighted) if (tags.has(tag)) add(`TAG_${tag.toUpperCase().replace(/-/g,'_')}`,'tool',delta,{tag});
  const environment=(input.agentEnvironment??'').toLowerCase(); if(environment==='production')add('PRODUCTION_AGENT','environment',15,{environment});else if(environment==='staging')add('STAGING_AGENT','environment',7,{environment});else if(environment==='development')add('DEVELOPMENT_AGENT','environment',-3,{environment});
  if(!input.agentEnabled)add('AGENT_DISABLED','agent',20); if(input.defaultDecisionUsed)add('NO_MATCHING_POLICY','authorization',15); if(input.policyDecision==='DENY')add('POLICY_DENY','authorization',10);else if(input.policyDecision==='REQUIRE_APPROVAL')add('HUMAN_APPROVAL_REQUIRED','approval',-10);else add('POLICY_ALLOW','authorization',3);
  if(input.grantRequired&&!input.grantAllowed)add('GRANT_REQUIRED_OR_INVALID','grant',18);else if(input.grantAllowed&&input.grantMaxExecutions===1)add('ONE_SHOT_GRANT','grant',-10);else if(input.grantAllowed&&(input.grantMaxExecutions??0)>=50)add('HIGH_EXECUTION_GRANT','grant',10,{maxExecutions:input.grantMaxExecutions!}); if(input.grantAllowed&&input.grantExpiresAt&&input.grantExpiresAt.getTime()-evaluatedAt.getTime()<300000)add('GRANT_NEAR_EXPIRATION','grant',5);
  try{const host=new URL(input.url).hostname;add('PUBLIC_EGRESS_TARGET','egress',6,{host});}catch{add('INVALID_EGRESS_TARGET','egress',20);} const score=Math.max(0,Math.min(100,factors.reduce((sum,f)=>sum+f.scoreDelta,10))); return {score,level:riskLevel(score),factors,evaluatedAt:evaluatedAt.toISOString(),riskModelVersion:'v1'};
}
