import test from 'node:test'; import assert from 'node:assert/strict'; import { createServer } from 'node:http'; import { mkdtempSync, readFileSync } from 'node:fs'; import { tmpdir } from 'node:os'; import { join } from 'node:path';
import { createLocalAAV, EnvironmentCredentialProvider } from '../dist/index.js'; import { SQLiteStorage } from '@agentactionverifier/storage-sqlite'; import { verifyReceipt } from '@agentactionverifier/verifier/verifyReceipt';
const secret='dummy-local-secret-never-expose';
async function listenTool(){let calls={allow:0,deny:0,approval:0,idem:0},headers=[];const server=createServer(async(req,res)=>{const body=[];for await(const c of req)body.push(c);const key=req.url.slice(1);calls[key]=(calls[key]??0)+1;headers.push(req.headers.authorization);if(key==='slow')return setTimeout(()=>{res.writeHead(200,{'content-type':'application/json'});res.end('{}');},200);res.writeHead(200,{'content-type':'application/json'});res.end(JSON.stringify({ok:true,key,input:JSON.parse(Buffer.concat(body).toString()||'{}')}));});await new Promise(r=>server.listen(0,'127.0.0.1',r));return{server,calls,headers,url:`http://127.0.0.1:${server.address().port}`};}
const request=(base,token,path,init={})=>fetch(base+path,{...init,headers:{authorization:`Bearer ${token}`,...init.headers}});
test('real Local E2E: auth, policies, credentials, receipts, idempotency, approvals and restart',async(t)=>{const dir=mkdtempSync(join(tmpdir(),'aav-local-')),path=join(dir,'aav.db'),toolServer=await listenTool();let runtime,db;t.after(async()=>{await runtime?.stop().catch(()=>{});try{db?.close();}catch{}await new Promise(r=>toolServer.server.close(r));});let resolutions=0,logs=[];const provider={async resolve(){resolutions++;return secret;}};const tools=['allow','deny','approval','idem'].map(key=>({key,name:key,method:'POST',url:`${toolServer.url}/${key}`,credentialRef:'token',networkPolicy:{allowLoopback:true}}));const policies=[{id:'allow',name:'allow',decision:'ALLOW',toolKey:'allow',priority:10},{id:'deny',name:'deny',decision:'DENY',toolKey:'deny',priority:10},{id:'approval',name:'approval',decision:'REQUIRE_APPROVAL',toolKey:'approval',priority:10},{id:'idem',name:'idem',decision:'ALLOW',toolKey:'idem',priority:10}];db=new SQLiteStorage(path);runtime=createLocalAAV({project:{id:'p1',name:'Project'},agent:{id:'a1',name:'Agent'},stores:db,credentials:provider,tools,policies,port:0,logger:e=>logs.push(e)});const token=runtime.bootstrapToken;assert.ok(token&&token.length>=40);assert.equal(runtime.bootstrapToken,undefined);await runtime.start();const base=runtime.url;
  tools.push({key:'slow',name:'slow',method:'POST',url:`${toolServer.url}/slow`,credentialRef:'token',networkPolicy:{allowLoopback:true},timeoutMs:10},{key:'failure',name:'failure',method:'POST',url:`${toolServer.url}/failure`,credentialRef:'token',networkPolicy:{allowLoopback:true}});policies.push({id:'slow',name:'slow',decision:'ALLOW',toolKey:'slow',priority:10},{id:'failure',name:'failure',decision:'ALLOW',toolKey:'failure',priority:10});runtime.registerTool(tools.at(-2));runtime.registerTool(tools.at(-1));runtime.addPolicy(policies.at(-2));runtime.addPolicy(policies.at(-1));
  assert.equal((await fetch(base+'/v1/agent/me')).status,401);assert.equal((await request(base,token,'/v1/agent/me',{headers:{origin:'https://evil.example'}})).status,403);assert.equal((await request(base,token,'/v1/agent/me')).status,200);
  assert.equal((await(await request(base,token,'/v1/agent/me')).json()).agentId,'a1');assert.ok((await(await request(base,token,'/v1/agent/tools')).json()).some(x=>x.toolKey==='allow'));const allowedBody=await(await request(base,token,'/v1/agent/tools/allow/execute',{method:'POST',headers:{'content-type':'application/json'},body:'{"input":{"value":1}}'})).json();assert.equal(toolServer.calls.allow,1);assert.equal(toolServer.headers.at(-1),`Bearer ${secret}`);assert.equal(JSON.stringify(allowedBody).includes(secret),false);const events=await(await request(base,token,`/v1/agent/runs/${allowedBody.runId}/events`)).json(),receipt=await (await request(base,token,`/v1/agent/runs/${allowedBody.runId}/receipt`)).json();assert.deepEqual(verifyReceipt(receipt,events),{ok:true});assert.equal(JSON.stringify(events).includes(secret),false);
  const before=resolutions,denied=await request(base,token,'/v1/agent/tools/deny/execute',{method:'POST',headers:{'content-type':'application/json'},body:'{"input":{}}'}),deniedBody=await denied.json();assert.equal(denied.status,403);assert.equal(toolServer.calls.deny,0);assert.equal(resolutions,before);const denyEvents=await(await request(base,token,`/v1/agent/runs/${deniedBody.error.runId}/events`)).json(),denyReceipt=await(await request(base,token,`/v1/agent/runs/${deniedBody.error.runId}/receipt`)).json();assert.ok(denyEvents.some(e=>e.type==='POLICY_EVALUATED'));assert.deepEqual(verifyReceipt(denyReceipt,denyEvents),{ok:true});
  const idemCalls=await Promise.all(Array.from({length:20},()=>request(base,token,'/v1/agent/tools/idem/execute',{method:'POST',headers:{'content-type':'application/json','idempotency-key':'same'},body:'{"input":{"x":1}}'}).then(r=>r.json())));assert.equal(toolServer.calls.idem,1);assert.equal(new Set(idemCalls.map(x=>x.runId)).size,1);
  const pending=await request(base,token,'/v1/agent/tools/approval/execute',{method:'POST',headers:{'content-type':'application/json'},body:'{"input":{"x":1}}'}),pendingBody=await pending.json();assert.equal(pending.status,403);assert.equal(toolServer.calls.approval,0);const approvalId=pendingBody.error.approvalRequestId;const decisions=await Promise.all(Array.from({length:10},()=>request(base,token,`/v1/local/approvals/${approvalId}/approve`,{method:'POST',headers:{'content-type':'application/json'},body:'{}'})));assert.ok(decisions.every(x=>x.status===200));assert.equal(toolServer.calls.approval,1);const approvalEvents=await(await request(base,token,`/v1/agent/runs/${pendingBody.error.runId}/events`)).json(),approvalReceipt=await(await request(base,token,`/v1/agent/runs/${pendingBody.error.runId}/receipt`)).json();assert.deepEqual(verifyReceipt(approvalReceipt,approvalEvents),{ok:true});
  const rejected=await request(base,token,'/v1/agent/tools/approval/execute',{method:'POST',headers:{'content-type':'application/json'},body:'{"input":{"reject":true}}'}),rejectedBody=await rejected.json();await request(base,token,`/v1/local/approvals/${rejectedBody.error.approvalRequestId}/reject`,{method:'POST',headers:{'content-type':'application/json'},body:'{}'});assert.equal(toolServer.calls.approval,1);
  const parallel=await Promise.all(Array.from({length:5},(_,i)=>request(base,token,'/v1/agent/tools/allow/execute',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({input:{parallel:i}})}).then(r=>r.json())));assert.equal(new Set(parallel.map(x=>x.runId)).size,5);for(const item of parallel){const ev=await(await request(base,token,`/v1/agent/runs/${item.runId}/events`)).json();assert.deepEqual(ev.map(x=>x.seq),Array.from({length:ev.length},(_,i)=>i+1));}
  const survivor=await request(base,token,'/v1/agent/tools/approval/execute',{method:'POST',headers:{'content-type':'application/json'},body:'{"input":{"survive":true}}'}),survivorBody=await survivor.json();
  const dryBefore=toolServer.calls.allow,dry=await request(base,token,'/v1/agent/tools/allow/dry-run',{method:'POST',headers:{'content-type':'application/json'},body:'{"input":{}}'});assert.equal(dry.status,200);assert.equal(toolServer.calls.allow,dryBefore);
  const timed=await request(base,token,'/v1/agent/tools/slow/execute',{method:'POST',headers:{'content-type':'application/json'},body:'{"input":{}}'});assert.equal(timed.status,504);const timedBody=await timed.json();assert.equal(timedBody.error.code,'DOWNSTREAM_TIMEOUT');
  assert.equal(JSON.stringify(logs).includes(secret),false);for(const table of ['runs','audit_events','receipts','approvals','idempotency'])assert.equal(JSON.stringify(db.db.prepare(`SELECT * FROM ${table}`).all()).includes(secret),false);
  const savedRun=allowedBody.runId;await runtime.stop();db.close();db=new SQLiteStorage(path);runtime=createLocalAAV({project:{id:'p1',name:'Project'},agent:{id:'a1',name:'Agent'},stores:db,credentials:provider,tools,policies,auth:{token},port:0});await runtime.start();assert.equal((await request(runtime.url,token,`/v1/agent/runs/${savedRun}`)).status,200);assert.equal((await request(runtime.url,token,`/v1/agent/approvals/${survivorBody.error.approvalRequestId}`)).status,200);const replay=await request(runtime.url,token,'/v1/agent/tools/idem/execute',{method:'POST',headers:{'content-type':'application/json','idempotency-key':'same'},body:'{"input":{"x":1}}'});assert.equal(replay.status,200);assert.equal(toolServer.calls.idem,1);await runtime.stop();db.close();await new Promise(r=>toolServer.server.close(r));assert.equal(readFileSync(path).includes(Buffer.from(secret)),false);});
test('network policy blocks loopback unless explicitly enabled',async()=>{const { safeHttpFetch }=await import('../dist/network.js');await assert.rejects(()=>safeHttpFetch('http://127.0.0.1:1',{}, {timeoutMs:50,responseMaxBytes:10}),e=>e.code==='EGRESS_DESTINATION_BLOCKED');});
test('environment credentials resolve only configured references',async()=>{const p=new EnvironmentCredentialProvider({github:'GITHUB_TOKEN'},{GITHUB_TOKEN:'x'});assert.equal(await p.resolve('github'),'x');assert.equal(await p.resolve('unknown'),undefined);});
