import { DatabaseSync } from 'node:sqlite';
import type { AuditEvent, JsonValue, Receipt } from '@agentactionverifier/protocol/audit';

export type LocalProject={id:string;name:string;tokenHash:string};
export type LocalAgent={id:string;projectId:string;name:string;enabled:boolean};
export type LocalTool={id:string;projectId:string;key:string;name:string;method:string;url:string;inputSchema:JsonValue|null;outputSchema:JsonValue|null;credentialRef:string|null;credentialHeader:string|null;timeoutMs:number;responseMaxBytes:number;enabled:boolean;tags:string[];networkPolicy:{allowLoopback:boolean;allowPrivateRanges:boolean}};
export type LocalPolicy={id:string;projectId:string;name:string;enabled:boolean;priority:number;decision:string;toolKey:string|null;agentId:string|null;method:string|null;requiredTags:string[];createdAt:string};
export type LocalRun={id:string;projectId:string;agentId:string;toolKey:string;status:string;startedAt:string;finishedAt:string|null;finalChainHash:string;resultJson:JsonValue|null};
export type LocalApproval={id:string;projectId:string;runId:string;agentId:string;toolKey:string;policyId:string|null;contextHash:string;status:string;input:JsonValue;expiresAt:string;decidedAt:string|null};
export type MCPUpstreamRow={id:string;projectId:string;name:string;transport:string;config:JsonValue;enabled:boolean};
export type MCPToolMappingRow={projectId:string;toolKey:string;upstreamId:string;upstreamTool:string;metadata:JsonValue};
const parse=<T>(v:unknown):T=>JSON.parse(String(v)) as T;

export class SQLiteStorage {
  readonly db:DatabaseSync;
  private transactionDepth=0;
  constructor(path:string){this.db=new DatabaseSync(path);this.db.exec(`PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON; PRAGMA busy_timeout=5000; CREATE TABLE IF NOT EXISTS schema_meta(version INTEGER NOT NULL); INSERT INTO schema_meta(version) SELECT 1 WHERE NOT EXISTS(SELECT 1 FROM schema_meta); CREATE TABLE IF NOT EXISTS projects(id TEXT PRIMARY KEY,name TEXT NOT NULL,token_hash TEXT NOT NULL); CREATE TABLE IF NOT EXISTS agents(id TEXT PRIMARY KEY,project_id TEXT NOT NULL REFERENCES projects(id),name TEXT NOT NULL,enabled INTEGER NOT NULL); CREATE TABLE IF NOT EXISTS tools(id TEXT PRIMARY KEY,project_id TEXT NOT NULL REFERENCES projects(id),tool_key TEXT NOT NULL,name TEXT NOT NULL,method TEXT NOT NULL,url TEXT NOT NULL,input_schema TEXT,output_schema TEXT,credential_ref TEXT,credential_header TEXT,timeout_ms INTEGER NOT NULL,response_max_bytes INTEGER NOT NULL,enabled INTEGER NOT NULL,tags TEXT NOT NULL,network_policy TEXT NOT NULL,UNIQUE(project_id,tool_key)); CREATE TABLE IF NOT EXISTS policies(id TEXT PRIMARY KEY,project_id TEXT NOT NULL REFERENCES projects(id),name TEXT NOT NULL,enabled INTEGER NOT NULL,priority INTEGER NOT NULL,decision TEXT NOT NULL,tool_key TEXT,agent_id TEXT,method TEXT,required_tags TEXT NOT NULL,created_at TEXT NOT NULL); CREATE TABLE IF NOT EXISTS runs(id TEXT PRIMARY KEY,project_id TEXT NOT NULL REFERENCES projects(id),agent_id TEXT NOT NULL,tool_key TEXT NOT NULL,status TEXT NOT NULL,started_at TEXT NOT NULL,finished_at TEXT,final_chain_hash TEXT NOT NULL,result_json TEXT); CREATE TABLE IF NOT EXISTS audit_events(id TEXT PRIMARY KEY,run_id TEXT NOT NULL REFERENCES runs(id),seq INTEGER NOT NULL,type TEXT NOT NULL,at TEXT NOT NULL,data TEXT,event_hash TEXT NOT NULL,prev_chain_hash TEXT NOT NULL,chain_hash TEXT NOT NULL,UNIQUE(run_id,seq)); CREATE TABLE IF NOT EXISTS receipts(run_id TEXT PRIMARY KEY REFERENCES runs(id),event_count INTEGER NOT NULL,final_chain_hash TEXT NOT NULL,issued_at TEXT NOT NULL); CREATE TABLE IF NOT EXISTS approvals(id TEXT PRIMARY KEY,project_id TEXT NOT NULL REFERENCES projects(id),run_id TEXT NOT NULL REFERENCES runs(id),agent_id TEXT NOT NULL,tool_key TEXT NOT NULL,policy_id TEXT,context_hash TEXT NOT NULL,status TEXT NOT NULL,input_json TEXT NOT NULL,expires_at TEXT NOT NULL,decided_at TEXT); CREATE TABLE IF NOT EXISTS idempotency(project_id TEXT NOT NULL,key TEXT NOT NULL,fingerprint TEXT NOT NULL,status TEXT NOT NULL,response_json TEXT,run_id TEXT,PRIMARY KEY(project_id,key));`);this.migrate();}
  private migrate(){const version=(this.db.prepare('SELECT version FROM schema_meta').get() as {version:number}).version;if(version<2)this.transaction(()=>{this.db.exec(`CREATE TABLE IF NOT EXISTS mcp_upstreams(id TEXT NOT NULL,project_id TEXT NOT NULL REFERENCES projects(id),name TEXT NOT NULL,transport TEXT NOT NULL,config_json TEXT NOT NULL,enabled INTEGER NOT NULL,PRIMARY KEY(project_id,id)); CREATE TABLE IF NOT EXISTS mcp_tool_mappings(project_id TEXT NOT NULL REFERENCES projects(id),tool_key TEXT NOT NULL,upstream_id TEXT NOT NULL,upstream_tool TEXT NOT NULL,metadata_json TEXT NOT NULL,PRIMARY KEY(project_id,tool_key),UNIQUE(project_id,upstream_id,upstream_tool)); UPDATE schema_meta SET version=2;`);});}
  close(){this.db.close();}
  transaction<T>(fn:()=>T):T{if(this.transactionDepth)return fn();this.db.exec('BEGIN IMMEDIATE');this.transactionDepth++;try{const out=fn();this.db.exec('COMMIT');return out;}catch(e){this.db.exec('ROLLBACK');throw e;}finally{this.transactionDepth--;}}
  bootstrapProject(v:LocalProject){this.db.prepare('INSERT INTO projects(id,name,token_hash) VALUES(?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name').run(v.id,v.name,v.tokenHash);}
  project(id:string){const r=this.db.prepare('SELECT id,name,token_hash tokenHash FROM projects WHERE id=?').get(id);return r as LocalProject|undefined;}
  putAgent(v:LocalAgent){this.db.prepare('INSERT OR REPLACE INTO agents VALUES(?,?,?,?)').run(v.id,v.projectId,v.name,+v.enabled);}
  agent(id:string){const r=this.db.prepare('SELECT id,project_id projectId,name,enabled FROM agents WHERE id=?').get(id) as any;return r?{...r,enabled:Boolean(r.enabled)}:undefined;}
  putTool(v:LocalTool){this.db.prepare('INSERT OR REPLACE INTO tools VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(v.id,v.projectId,v.key,v.name,v.method,v.url,v.inputSchema===null?null:JSON.stringify(v.inputSchema),v.outputSchema===null?null:JSON.stringify(v.outputSchema),v.credentialRef,v.credentialHeader,v.timeoutMs,v.responseMaxBytes,+v.enabled,JSON.stringify(v.tags),JSON.stringify(v.networkPolicy));}
  tools(projectId:string){return (this.db.prepare('SELECT * FROM tools WHERE project_id=? ORDER BY tool_key').all(projectId) as any[]).map(toolRow);}
  tool(projectId:string,key:string){const r=this.db.prepare('SELECT * FROM tools WHERE project_id=? AND tool_key=?').get(projectId,key) as any;return r?toolRow(r):undefined;}
  putPolicy(v:LocalPolicy){this.db.prepare('INSERT OR REPLACE INTO policies VALUES(?,?,?,?,?,?,?,?,?,?,?)').run(v.id,v.projectId,v.name,+v.enabled,v.priority,v.decision,v.toolKey,v.agentId,v.method,JSON.stringify(v.requiredTags),v.createdAt);}
  policies(projectId:string){return (this.db.prepare('SELECT * FROM policies WHERE project_id=?').all(projectId) as any[]).map((r)=>({id:r.id,projectId:r.project_id,name:r.name,enabled:Boolean(r.enabled),priority:r.priority,decision:r.decision,toolKey:r.tool_key,agentId:r.agent_id,method:r.method,requiredTags:parse<string[]>(r.required_tags),createdAt:r.created_at}));}
  createRun(v:LocalRun){this.db.prepare('INSERT INTO runs VALUES(?,?,?,?,?,?,?,?,?)').run(v.id,v.projectId,v.agentId,v.toolKey,v.status,v.startedAt,v.finishedAt,v.finalChainHash,v.resultJson===null?null:JSON.stringify(v.resultJson));}
  run(id:string){const r=this.db.prepare('SELECT * FROM runs WHERE id=?').get(id) as any;return r?runRow(r):undefined;}
  updateRun(id:string,v:{status:string;finishedAt:string;finalChainHash:string;resultJson:JsonValue|null}){this.db.prepare('UPDATE runs SET status=?,finished_at=?,final_chain_hash=?,result_json=? WHERE id=?').run(v.status,v.finishedAt,v.finalChainHash,v.resultJson===null?null:JSON.stringify(v.resultJson),id);}
  events(runId:string){return (this.db.prepare('SELECT * FROM audit_events WHERE run_id=? ORDER BY seq').all(runId) as any[]).map(eventRow);}
  appendEvent(event:AuditEvent){this.db.prepare('INSERT INTO audit_events VALUES(?,?,?,?,?,?,?,?,?)').run(event.id,event.runId,event.seq,event.type,event.at,event.data===undefined?null:JSON.stringify(event.data),event.eventHash!,event.prevChainHash!,event.chainHash!);}
  putReceipt(v:Receipt){this.db.prepare('INSERT OR REPLACE INTO receipts VALUES(?,?,?,?)').run(v.runId,v.eventCount,v.finalChainHash,v.issuedAt);}
  receipt(runId:string){return this.db.prepare('SELECT run_id runId,event_count eventCount,final_chain_hash finalChainHash,issued_at issuedAt FROM receipts WHERE run_id=?').get(runId) as Receipt|undefined;}
  putApproval(v:LocalApproval){this.db.prepare('INSERT INTO approvals VALUES(?,?,?,?,?,?,?,?,?,?,?)').run(v.id,v.projectId,v.runId,v.agentId,v.toolKey,v.policyId,v.contextHash,v.status,JSON.stringify(v.input),v.expiresAt,v.decidedAt);}
  approval(id:string){const r=this.db.prepare('SELECT * FROM approvals WHERE id=?').get(id) as any;return r?approvalRow(r):undefined;}
  approvals(projectId:string){return (this.db.prepare("SELECT * FROM approvals WHERE project_id=? ORDER BY expires_at").all(projectId) as any[]).map(approvalRow);}
  transitionApproval(id:string,from:string,to:string,now:string){return this.db.prepare('UPDATE approvals SET status=?,decided_at=? WHERE id=? AND status=? AND expires_at>?').run(to,now,id,from,now).changes===1;}
  claimIdempotency(projectId:string,key:string,fingerprint:string){try{this.db.prepare("INSERT INTO idempotency(project_id,key,fingerprint,status) VALUES(?,?,?,'IN_PROGRESS')").run(projectId,key,fingerprint);return'CLAIMED' as const;}catch{const row=this.db.prepare('SELECT fingerprint,status FROM idempotency WHERE project_id=? AND key=?').get(projectId,key) as any;return !row||row.fingerprint!==fingerprint?'CONFLICT' as const:row.status==='COMPLETE'?'COMPLETE' as const:'IN_PROGRESS' as const;}}
  completeIdempotency(projectId:string,key:string,response:JsonValue,runId:string){this.db.prepare("UPDATE idempotency SET status='COMPLETE',response_json=?,run_id=? WHERE project_id=? AND key=?").run(JSON.stringify(response),runId,projectId,key);}
  idempotency(projectId:string,key:string){const r=this.db.prepare('SELECT * FROM idempotency WHERE project_id=? AND key=?').get(projectId,key) as any;return r?{...r,response:r.response_json?parse<JsonValue>(r.response_json):null}:undefined;}
  putMCPUpstream(v:MCPUpstreamRow){this.db.prepare('INSERT OR REPLACE INTO mcp_upstreams VALUES(?,?,?,?,?,?)').run(v.id,v.projectId,v.name,v.transport,JSON.stringify(v.config),+v.enabled);}
  mcpUpstreams(projectId:string){return (this.db.prepare('SELECT * FROM mcp_upstreams WHERE project_id=? ORDER BY id').all(projectId) as any[]).map(r=>({id:r.id,projectId:r.project_id,name:r.name,transport:r.transport,config:parse<JsonValue>(r.config_json),enabled:Boolean(r.enabled)}));}
  putMCPToolMapping(v:MCPToolMappingRow){this.db.prepare('INSERT OR REPLACE INTO mcp_tool_mappings VALUES(?,?,?,?,?)').run(v.projectId,v.toolKey,v.upstreamId,v.upstreamTool,JSON.stringify(v.metadata));}
  mcpToolMappings(projectId:string){return (this.db.prepare('SELECT * FROM mcp_tool_mappings WHERE project_id=? ORDER BY tool_key').all(projectId) as any[]).map(r=>({projectId:r.project_id,toolKey:r.tool_key,upstreamId:r.upstream_id,upstreamTool:r.upstream_tool,metadata:parse<JsonValue>(r.metadata_json)}));}
}
function toolRow(r:any):LocalTool{return{id:r.id,projectId:r.project_id,key:r.tool_key,name:r.name,method:r.method,url:r.url,inputSchema:r.input_schema?parse(r.input_schema):null,outputSchema:r.output_schema?parse(r.output_schema):null,credentialRef:r.credential_ref,credentialHeader:r.credential_header,timeoutMs:r.timeout_ms,responseMaxBytes:r.response_max_bytes,enabled:Boolean(r.enabled),tags:parse(r.tags),networkPolicy:parse(r.network_policy)};}
function runRow(r:any):LocalRun{return{id:r.id,projectId:r.project_id,agentId:r.agent_id,toolKey:r.tool_key,status:r.status,startedAt:r.started_at,finishedAt:r.finished_at,finalChainHash:r.final_chain_hash,resultJson:r.result_json?parse(r.result_json):null};}
function eventRow(r:any):AuditEvent{return{id:r.id,runId:r.run_id,seq:r.seq,type:r.type,at:r.at,data:r.data?parse(r.data):undefined,eventHash:r.event_hash,prevChainHash:r.prev_chain_hash,chainHash:r.chain_hash};}
function approvalRow(r:any):LocalApproval{return{id:r.id,projectId:r.project_id,runId:r.run_id,agentId:r.agent_id,toolKey:r.tool_key,policyId:r.policy_id,contextHash:r.context_hash,status:r.status,input:parse(r.input_json),expiresAt:r.expires_at,decidedAt:r.decided_at};}
