#!/usr/bin/env node
import { createHash, randomBytes, randomUUID, timingSafeEqual } from 'node:crypto';
import { accessSync, constants, existsSync, mkdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { delimiter, dirname, isAbsolute, join } from 'node:path';
import { createServer } from 'node:net';
import { Server } from '@modelcontextprotocol/server';
import { StdioServerTransport } from '@modelcontextprotocol/server/stdio';
import { createLocalAAV, EnvironmentCredentialProvider } from '@agentactionverifier/gateway';
import { createAAVMCPProxy } from '@agentactionverifier/mcp';
import { SQLiteStorage } from '@agentactionverifier/storage-sqlite';
import { verifyReceipt } from '@agentactionverifier/verifier';
import { CLI_VERSION, EXIT } from './index.js';
import { initialConfig, loadConfig, paths, validateConfig, writeConfig, type LocalConfig } from './config.js';

const HELP=`AAV Local ${CLI_VERSION}\n\nUsage: aav <command> [options]\n\nCommands:\n  init [--force] [--name NAME]\n  start\n  status [--json]\n  doctor [--json]\n  mcp add <id> --transport stdio --command CMD [--arg VALUE] [--credential-env NAME]\n  mcp list [--json]\n  mcp remove <id>\n  policy list [--json]\n  policy add --tool ID:TOOL --decision ALLOW|DENY|REQUIRE_APPROVAL\n  approval list [--json]\n  approval approve <id>\n  approval reject <id>\n  runs list [--json]\n  runs show <runId> [--json]\n  receipt verify <file> [--json]\n\nEnvironment:\n  AAV_HOME        Override .aav directory (used by containers)\n  AAV_AUTH_TOKEN  Bootstrap token emitted once by aav init\n\nExit codes: 0 success, 2 usage, 3 configuration, 4 security, 5 runtime, 6 verification.`;
type Output={json:boolean};
const hash=(value:string)=>createHash('sha256').update(value).digest('hex');
const has=(args:string[],flag:string)=>args.includes(flag);
const value=(args:string[],flag:string)=>{const i=args.indexOf(flag);return i>=0?args[i+1]:undefined;};
const values=(args:string[],flag:string)=>args.flatMap((x,i)=>x===flag&&args[i+1]?[args[i+1]]:[]);
const print=(data:unknown,out:Output,human:string)=>{if(out.json)process.stdout.write(`${JSON.stringify(data)}\n`);else process.stdout.write(`${human}\n`);};
const fail=(message:string,code:number)=>{process.stderr.write(`AAV: ${message}\n`);process.exitCode=code;};
const openDb=()=>new SQLiteStorage(paths().db);
async function demoServer(){const server=new Server({name:'aav-safe-demo',version:'1.0.0'},{capabilities:{tools:{listChanged:false}}});let dangerousCalls=0;server.setRequestHandler('tools/list',async()=>({tools:[{name:'echo',description:'Returns supplied text.',inputSchema:{type:'object',properties:{text:{type:'string'}},required:['text']}},{name:'read_demo',description:'Returns harmless demo data.',inputSchema:{type:'object'}},{name:'dangerous_action',description:'Simulates a consequential action without side effects.',inputSchema:{type:'object',properties:{reason:{type:'string'}}},annotations:{destructiveHint:true}}]}) as any);server.setRequestHandler('tools/call',async request=>{const output=request.params.name==='echo'?{echo:request.params.arguments?.text}:request.params.name==='read_demo'?{records:['alpha','beta']}:{simulated:true,executed:++dangerousCalls};return{content:[{type:'text' as const,text:JSON.stringify(output)}]};});await server.connect(new StdioServerTransport());setInterval(()=>{},2147483647);}
function executable(command:string){if(isAbsolute(command)||command.includes('/')||command.includes('\\')){try{accessSync(command,constants.X_OK);return true;}catch{return false;}}for(const dir of (process.env.PATH??'').split(delimiter)){try{accessSync(join(dir,process.platform==='win32'?`${command}.exe`:command),constants.X_OK);return true;}catch{}}return false;}
async function portFree(host:string,port:number){return new Promise<boolean>(resolve=>{const server=createServer();server.once('error',()=>resolve(false));server.listen(port,host,()=>server.close(()=>resolve(true)));});}
function requireConfig(){try{return loadConfig();}catch(error){fail(error instanceof Error?error.message:'invalid configuration',EXIT.CONFIG);return undefined;}}
function credentialMap(config:LocalConfig){return Object.fromEntries(config.mcp.upstreams.flatMap(u=>u.credentialRef&&u.credentialEnv?[[u.credentialRef,u.credentialEnv]]:[]));}
function tokenMatches(db:SQLiteStorage,config:LocalConfig,token:string){const expected=db.project(config.project.id)?.tokenHash??'',a=Buffer.from(hash(token),'hex'),b=Buffer.from(expected,'hex');return a.length===b.length&&a.length===32&&timingSafeEqual(a,b);}

async function init(args:string[],out:Output){const p=paths();if(existsSync(p.config)&&!has(args,'--force'))return fail(`${p.config} already exists; use --force to replace it`,EXIT.CONFIG);for(const dir of [p.root,p.data,p.receipts,p.logs])mkdirSync(dir,{recursive:true,mode:0o700});const config=initialConfig(value(args,'--name')??dirname(process.cwd()).split('/').pop()??'aav-project');writeConfig(config);const token=randomBytes(32).toString('base64url'),db=openDb();db.bootstrapProject({id:config.project.id,name:config.project.name,tokenHash:hash(token)});db.close();const data={config:p.config,database:p.db,project:config.project,bootstrapToken:token};print(data,out,`Initialized AAV Local\nConfig: ${p.config}\nDatabase: ${p.db}\nProject: ${config.project.name}\n\nBootstrap token (shown once; not persisted):\n${token}\n\nSet AAV_AUTH_TOKEN before starting.`);}
async function start(){const config=requireConfig();if(!config)return;const token=process.env.AAV_AUTH_TOKEN;if(!token)return fail('AAV_AUTH_TOKEN is required (use the one-time token from aav init)',EXIT.CONFIG);const db=openDb();if(!tokenMatches(db,config,token)){db.close();return fail('AAV_AUTH_TOKEN does not match this project',EXIT.SECURITY);}const credentials=new EnvironmentCredentialProvider(credentialMap(config),process.env);const runtime=createLocalAAV({project:config.project,agent:{id:'local-cli',name:'AAV CLI'},stores:db,credentials,policies:config.policies,auth:{token},bind:config.server.host,port:config.server.port});const proxy=createAAVMCPProxy({projectId:config.project.id,runtime,stores:db,upstreams:config.mcp.upstreams});try{await proxy.start();await runtime.start();process.stderr.write(`AAV Local started\nHTTP: ${runtime.url}\nMCP: stdio\nProject: ${config.project.name}\nPolicy: default DENY\nCloud: disabled\n`);await proxy.connect(new StdioServerTransport());const shutdown=async()=>{await proxy.stop();await runtime.stop();db.close();};process.once('SIGINT',()=>void shutdown().finally(()=>process.exit(0)));process.once('SIGTERM',()=>void shutdown().finally(()=>process.exit(0)));}catch(error){await proxy.stop().catch(()=>{});await runtime.stop().catch(()=>{});db.close();fail(error instanceof Error?error.message:'runtime failed',EXIT.RUNTIME);}}
async function doctor(out:Output){const checks:Array<{status:'PASS'|'WARN'|'FAIL';check:string;detail:string}>=[];checks.push({status:process.versions.node.split('.').map(Number)[0]>=24?'PASS':'FAIL',check:'node',detail:`Node.js ${process.version}`});let config:LocalConfig|undefined;try{config=loadConfig();checks.push({status:'PASS',check:'configuration',detail:'valid schema v1'});}catch(error){checks.push({status:'FAIL',check:'configuration',detail:error instanceof Error?error.message:'invalid'});}if(config){try{const db=openDb(),version=(db.db.prepare('SELECT version FROM schema_meta').get() as any).version;checks.push({status:version===2?'PASS':'FAIL',check:'sqlite',detail:`schema v${version}`});db.close();}catch(error){checks.push({status:'FAIL',check:'sqlite',detail:error instanceof Error?error.message:'unavailable'});}for(const u of config.mcp.upstreams){checks.push({status:executable(u.command)?'PASS':'FAIL',check:`mcp:${u.id}`,detail:executable(u.command)?'executable found':'executable missing'});if(u.credentialEnv)checks.push({status:process.env[u.credentialEnv]?'PASS':'WARN',check:`env:${u.credentialEnv}`,detail:process.env[u.credentialEnv]?'set':'not set'});}checks.push({status:await portFree(config.server.host,config.server.port)?'PASS':'WARN',check:'port',detail:`${config.server.host}:${config.server.port} ${await portFree(config.server.host,config.server.port)?'available':'in use'}`});try{accessSync(paths().root,constants.R_OK|constants.W_OK);checks.push({status:'PASS',check:'filesystem',detail:'read/write'});}catch{checks.push({status:'FAIL',check:'filesystem',detail:'not writable'});}}const errors=checks.filter(x=>x.status==='FAIL').length,warnings=checks.filter(x=>x.status==='WARN').length;print({checks,result:{warnings,errors}},out,`AAV Doctor\n\n${checks.map(x=>`[${x.status}] ${x.check}: ${x.detail}`).join('\n')}\n\nResult: ${warnings} warning(s), ${errors} error(s)`);if(errors)process.exitCode=EXIT.RUNTIME;}
async function status(out:Output){const config=requireConfig();if(!config)return;const db=openDb(),policyCount=(db.db.prepare('SELECT count(*) n FROM policies WHERE project_id=?').get(config.project.id) as any).n,approvals=(db.db.prepare("SELECT count(*) n FROM approvals WHERE project_id=? AND status='PENDING'").get(config.project.id) as any).n,runs=(db.db.prepare('SELECT count(*) n FROM runs WHERE project_id=?').get(config.project.id) as any).n;db.close();let runtime:'RUNNING'|'CONFIGURED'|'UNKNOWN'='CONFIGURED';const token=process.env.AAV_AUTH_TOKEN;try{if(token&&(await fetch(`http://${config.server.host}:${config.server.port}/v1/agent/me`,{headers:{authorization:`Bearer ${token}`},signal:AbortSignal.timeout(500)})).ok)runtime='RUNNING';else runtime='UNKNOWN';}catch{}const data={project:config.project,database:paths().db,upstreams:config.mcp.upstreams.length,policies:Math.max(config.policies.length,policyCount),pendingApprovals:approvals,runs,runtime,endpoint:`http://${config.server.host}:${config.server.port}`};print(data,out,`AAV Local status\nProject: ${config.project.name}\nRuntime: ${runtime}\nDatabase: ${paths().db}\nUpstreams: ${data.upstreams}\nPolicies: ${data.policies}\nPending approvals: ${approvals}\nRuns: ${runs}`);}
function mcp(args:string[],out:Output){const config=requireConfig();if(!config)return;const action=args[0];if(action==='list')return print(config.mcp.upstreams,out,config.mcp.upstreams.length?config.mcp.upstreams.map(u=>`${u.id}\t${u.transport}\t${u.command}\t${u.credentialEnv?`env:${u.credentialEnv}`:'no credential'}`).join('\n'):'No MCP upstreams configured.');if(action==='add'){const id=args[1],command=value(args,'--command'),transport=value(args,'--transport')??'stdio',credentialEnv=value(args,'--credential-env');if(!id||!command||transport!=='stdio'||!/^[a-z0-9][a-z0-9_-]{0,63}$/.test(id))return fail('usage: aav mcp add <id> --transport stdio --command CMD [--arg VALUE] [--credential-env NAME]',EXIT.USAGE);if(config.mcp.upstreams.some(x=>x.id===id))return fail(`upstream ${id} already exists`,EXIT.CONFIG);if(credentialEnv&&!/^[A-Za-z_][A-Za-z0-9_]*$/.test(credentialEnv))return fail('invalid credential environment variable name',EXIT.CONFIG);config.mcp.upstreams.push({id,name:id,transport:'stdio',command,args:values(args,'--arg'),...(credentialEnv?{credentialRef:`env:${credentialEnv}`,credentialEnv}:{})});writeConfig(config);return print({id,transport,command,credentialSource:credentialEnv?`env:${credentialEnv}`:null,status:'configured'},out,`Added MCP upstream: ${id}\nTransport: stdio\nCredential source: ${credentialEnv?`env:${credentialEnv}`:'none'}\nStatus: configured`);}if(action==='remove'){const id=args[1],before=config.mcp.upstreams.length;config.mcp.upstreams=config.mcp.upstreams.filter(x=>x.id!==id);if(config.mcp.upstreams.length===before)return fail(`unknown upstream: ${id}`,EXIT.CONFIG);writeConfig(config);return print({removed:id},out,`Removed MCP upstream: ${id}`);}fail('usage: aav mcp add|list|remove',EXIT.USAGE);}
function policy(args:string[],out:Output){const config=requireConfig();if(!config)return;if(args[0]==='list')return print(config.policies,out,config.policies.length?config.policies.map(p=>`${p.toolKey}\t${p.decision}`).join('\n'):'No explicit policies. Default: DENY.');if(args[0]==='add'){const tool=value(args,'--tool'),decision=value(args,'--decision');if(!tool||!decision||!['ALLOW','DENY','REQUIRE_APPROVAL'].includes(decision)||!/^[a-z0-9][a-z0-9_-]{0,63}:[-A-Za-z0-9_.:]+$/.test(tool))return fail('usage: aav policy add --tool UPSTREAM:TOOL --decision ALLOW|DENY|REQUIRE_APPROVAL',EXIT.USAGE);if(!config.mcp.upstreams.some(x=>tool.startsWith(`${x.id}:`)))return fail('tool must reference a configured upstream',EXIT.CONFIG);const item={id:randomUUID(),name:`CLI ${decision} ${tool}`,decision:decision as any,toolKey:tool,priority:100};config.policies.push(item);writeConfig(config);return print(item,out,`Added policy: ${decision} ${tool}`);}fail('usage: aav policy add|list',EXIT.USAGE);}
async function approval(args:string[],out:Output){const config=requireConfig();if(!config)return;if(args[0]==='list'){const db=openDb(),rows=db.approvals(config.project.id).map(a=>({id:a.id,runId:a.runId,status:a.status,tool:a.toolKey,agent:a.agentId,expiresAt:a.expiresAt,arguments:a.input}));db.close();return print(rows,out,rows.length?rows.map(x=>`${x.id}\t${x.status}\t${x.tool}\t${JSON.stringify(x.arguments).slice(0,160)}`).join('\n'):'No approvals.');}if(['approve','reject'].includes(args[0])&&args[1]){const token=process.env.AAV_AUTH_TOKEN;if(!token)return fail('AAV_AUTH_TOKEN is required',EXIT.CONFIG);try{const response=await fetch(`http://${config.server.host}:${config.server.port}/v1/local/approvals/${encodeURIComponent(args[1])}/${args[0]}`,{method:'POST',headers:{authorization:`Bearer ${token}`,'content-type':'application/json'},body:'{}'}),body=await response.json();if(!response.ok)return fail(`approval failed: ${(body as any)?.error?.code??response.status}`,EXIT.SECURITY);return print(body,out,`Approval ${args[0]}d: ${args[1]}`);}catch{return fail('AAV Local is not running',EXIT.RUNTIME);}}fail('usage: aav approval list|approve <id>|reject <id>',EXIT.USAGE);}
function runs(args:string[],out:Output){const config=requireConfig();if(!config)return;const db=openDb();if(args[0]==='list'){const rows=db.db.prepare('SELECT id,tool_key tool,status,started_at startedAt,finished_at finishedAt FROM runs WHERE project_id=? ORDER BY started_at DESC LIMIT 50').all(config.project.id);db.close();return print(rows,out,(rows as any[]).length?(rows as any[]).map(x=>`${x.id}\t${x.status}\t${x.tool}\t${x.startedAt}`).join('\n'):'No runs.');}if(args[0]==='show'&&args[1]){const run=db.run(args[1]);if(!run){db.close();return fail('run not found',EXIT.CONFIG);}const events=db.events(args[1]),receipt=db.receipt(args[1])??null;db.close();const data={run,events,receipt,receiptStatus:receipt?verifyReceipt(receipt,events):null};return print(data,out,`Run: ${run.id}\nTool: ${run.toolKey}\nStatus: ${run.status}\nEvents: ${events.length}\nReceipt: ${data.receiptStatus?.ok?'VALID':receipt?'INVALID':'NONE'}`);}db.close();fail('usage: aav runs list|show <runId>',EXIT.USAGE);}
function receipt(args:string[],out:Output){if(args[0]!=='verify'||!args[1])return fail('usage: aav receipt verify <file>',EXIT.USAGE);try{const parsed=JSON.parse(readFileSync(args[1],'utf8')),result=verifyReceipt(parsed.receipt,parsed.events),data={...result,runId:parsed.receipt?.runId,eventCount:parsed.receipt?.eventCount,finalChainHash:parsed.receipt?.finalChainHash};print(data,out,result.ok?`Receipt valid\nRun: ${data.runId}\nEvents: ${data.eventCount}\nFinal chain hash: ${data.finalChainHash}\nVerification: PASS`:`Receipt invalid\nVerification: FAIL\nReason: ${(result as any).reason??'INVALID_RECEIPT'}`);if(!result.ok)process.exitCode=EXIT.VERIFICATION;}catch(error){fail(error instanceof Error?error.message:'invalid receipt file',EXIT.VERIFICATION);}}

async function main(){const args=process.argv.slice(2),out={json:has(args,'--json')};if(!args.length||has(args,'--help')||args[0]==='help')return process.stdout.write(`${HELP}\n`);if(has(args,'--version')||args[0]==='version')return process.stdout.write(`${CLI_VERSION}\n`);const clean=args.filter(x=>x!=='--json');switch(clean[0]){case'init':return init(clean.slice(1),out);case'start':return start();case'demo-server':return demoServer();case'doctor':return doctor(out);case'status':return status(out);case'mcp':return mcp(clean.slice(1),out);case'policy':return policy(clean.slice(1),out);case'approval':return approval(clean.slice(1),out);case'runs':return runs(clean.slice(1),out);case'receipt':return receipt(clean.slice(1),out);default:return fail(`unknown command: ${clean[0]}\nRun aav --help`,EXIT.USAGE);}}
main().catch(error=>fail(error instanceof Error?error.message:'unexpected failure',EXIT.RUNTIME));
