import { lstatSync, mkdirSync, readFileSync, renameSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { randomUUID } from 'node:crypto';
import { parseAAVLocalMCPConfig, type MCPUpstream } from '@agentactionverifier/mcp';
import type { PolicyConfig } from '@agentactionverifier/gateway';

export type LocalConfig={version:1;project:{id:string;name:string};server:{host:'127.0.0.1';port:number};mcp:{upstreams:MCPUpstream[]};policies:PolicyConfig[]};
export const home=(cwd=process.cwd())=>resolve(process.env.AAV_HOME??join(cwd,'.aav'));
export const paths=(cwd=process.cwd())=>{const root=home(cwd);return{root,config:join(root,'config.json'),data:join(root,'data'),db:join(root,'data','aav.db'),receipts:join(root,'receipts'),logs:join(root,'logs')}};
export function validateConfig(value:unknown):LocalConfig{if(!value||typeof value!=='object')throw new Error('configuration must be an object');const raw=value as any;if(raw.version!==1)throw new Error('unsupported configuration version');const allowed=new Set(['version','project','server','mcp','policies']);for(const key of Object.keys(raw))if(!allowed.has(key))throw new Error(`unknown configuration key: ${key}`);if(!raw.project||typeof raw.project.id!=='string'||typeof raw.project.name!=='string'||!raw.project.id||!raw.project.name)throw new Error('project.id and project.name are required');if(!raw.server||raw.server.host!=='127.0.0.1'||!Number.isInteger(raw.server.port)||raw.server.port<1||raw.server.port>65535)throw new Error('server must use 127.0.0.1 and a valid port');parseAAVLocalMCPConfig({project:raw.project.id,mcp:raw.mcp});if(!Array.isArray(raw.policies))throw new Error('policies must be an array');for(const p of raw.policies)if(!p||typeof p.name!=='string'||!['ALLOW','DENY','REQUIRE_APPROVAL'].includes(p.decision)||typeof p.toolKey!=='string')throw new Error('invalid policy');return raw as LocalConfig;}
export function loadConfig(cwd=process.cwd()){const file=paths(cwd).config;let value;try{value=JSON.parse(readFileSync(file,'utf8'));}catch(error){throw new Error(`cannot read ${file}: ${error instanceof Error?error.message:'invalid JSON'}`);}return validateConfig(value);}
export function writeConfig(config:LocalConfig,cwd=process.cwd()){const file=paths(cwd).config;mkdirSync(dirname(file),{recursive:true,mode:0o700});try{if(lstatSync(file).isSymbolicLink())throw new Error('refusing to write a symlinked config');}catch(error){if((error as NodeJS.ErrnoException).code!=='ENOENT')throw error;}const temporary=`${file}.${process.pid}.tmp`;writeFileSync(temporary,`${JSON.stringify(config,null,2)}\n`,{mode:0o600});renameSync(temporary,file);}
export function initialConfig(name:string):LocalConfig{return{version:1,project:{id:randomUUID(),name},server:{host:'127.0.0.1',port:7331},mcp:{upstreams:[]},policies:[]};}
