import { createServer, type IncomingMessage, type ServerResponse } from 'node:http';
import { createHash, randomBytes, randomUUID, timingSafeEqual } from 'node:crypto';
import type { AddressInfo } from 'node:net';
import type { AuditEvent, AuditEventType, AuthorizationContext, JsonValue, PolicyDecision, Receipt } from '@agentactionverifier/protocol/audit';
import { AUDIT_CHAIN_GENESIS, computeAuditChainHash, computeAuditEventHash } from '@agentactionverifier/protocol/audit-chain';
import { canonicalJsonStringify } from '@agentactionverifier/protocol/canonical-json';
import { approvalContextHash, canTransition, evaluatePolicy, executionRequestFingerprint, matchesApprovalContext, validateToolInput } from '@agentactionverifier/core';
import type { CredentialProvider } from './credentials.js';
import { GatewayError, safeHttpFetch } from './network.js';
export { EnvironmentCredentialProvider } from './credentials.js'; export * from './network.js';

export type ProjectConfig={id:string;name:string}; export type AgentConfig={id:string;name:string;enabled?:boolean};
export type ToolConfig={id?:string;key:string;name:string;method:string;url:string;inputSchema?:JsonValue|null;outputSchema?:JsonValue|null;credentialRef?:string;credentialHeader?:string;timeoutMs?:number;responseMaxBytes?:number;enabled?:boolean;tags?:string[];networkPolicy?:{allowLoopback?:boolean;allowPrivateRanges?:boolean}};
export type LocalToolExecutor=(request:{toolKey:string;input:JsonValue;credential?:string})=>Promise<JsonValue>;
export type PolicyConfig={id?:string;name:string;enabled?:boolean;priority?:number;decision:PolicyDecision;toolKey?:string;agentId?:string;method?:string;requiredTags?:string[];createdAt?:string};
type StoredTool=Required<Omit<ToolConfig,'credentialRef'|'credentialHeader'|'inputSchema'|'outputSchema'|'networkPolicy'>>&{projectId:string;credentialRef:string|null;credentialHeader:string|null;inputSchema:JsonValue|null;outputSchema:JsonValue|null;networkPolicy:{allowLoopback:boolean;allowPrivateRanges:boolean}};
type StoredRun={id:string;projectId:string;agentId:string;toolKey:string;status:string;startedAt:string;finishedAt:string|null;finalChainHash:string;resultJson:JsonValue|null};
type StoredApproval={id:string;projectId:string;runId:string;agentId:string;toolKey:string;policyId:string|null;contextHash:string;status:string;input:JsonValue;expiresAt:string;decidedAt:string|null};
export interface LocalStores{transaction<T>(fn:()=>T):T;bootstrapProject(v:{id:string;name:string;tokenHash:string}):void;project(id:string):{id:string;name:string;tokenHash:string}|undefined;putAgent(v:{id:string;projectId:string;name:string;enabled:boolean}):void;agent(id:string):{id:string;projectId:string;name:string;enabled:boolean}|undefined;putTool(v:StoredTool):void;tools(projectId:string):StoredTool[];tool(projectId:string,key:string):StoredTool|undefined;putPolicy(v:any):void;policies(projectId:string):any[];createRun(v:StoredRun):void;run(id:string):StoredRun|undefined;updateRun(id:string,v:{status:string;finishedAt:string;finalChainHash:string;resultJson:JsonValue|null}):void;events(runId:string):AuditEvent[];appendEvent(event:AuditEvent):void;putReceipt(v:Receipt):void;receipt(runId:string):Receipt|undefined;putApproval(v:StoredApproval):void;approval(id:string):StoredApproval|undefined;approvals(projectId:string):StoredApproval[];transitionApproval(id:string,from:string,to:string,now:string):boolean;claimIdempotency(projectId:string,key:string,fingerprint:string):'CLAIMED'|'CONFLICT'|'COMPLETE'|'IN_PROGRESS';completeIdempotency(projectId:string,key:string,response:JsonValue,runId:string):void;idempotency(projectId:string,key:string):{response:JsonValue|null}|undefined;close?():void;}
export type LocalAAVConfig={project:ProjectConfig;agent:AgentConfig;stores:LocalStores;credentials:CredentialProvider;tools?:ToolConfig[];policies?:PolicyConfig[];auth?:{token?:string};bind?:string;port?:number;allowedOrigins?:string[];logger?:(event:Record<string,unknown>)=>void;clock?:{now():Date};executors?:Record<string,LocalToolExecutor>};

const hash=(v:string)=>createHash('sha256').update(v).digest('hex'); const asJson=(v:unknown)=>v as JsonValue;
const redact=(value:JsonValue,secret?:string):JsonValue=>{if(!secret)return value;if(typeof value==='string')return value.split(secret).join('[REDACTED]');if(Array.isArray(value))return value.map(v=>redact(v,secret));if(value&&typeof value==='object')return Object.fromEntries(Object.entries(value).map(([k,v])=>[k,redact(v,secret)]));return value;};
export function createLocalAAV(config:LocalAAVConfig){return new LocalAAV(config);}
export class LocalAAV{
  private server= createServer((req,res)=>void this.handle(req,res)); private token:string; private bootstrap:string|undefined; private inflight=new Map<string,Promise<{status:number;body:JsonValue}>>(); private clock:{now():Date}; private bind:string; private requestedPort:number;
  constructor(private config:LocalAAVConfig){this.bind=config.bind??'127.0.0.1';this.requestedPort=config.port??7331;if(this.bind==='0.0.0.0')throw new Error('Wildcard binding is not allowed');this.clock=config.clock??{now:()=>new Date()};this.token=config.auth?.token??randomBytes(32).toString('base64url');this.bootstrap=config.auth?.token?undefined:this.token;config.stores.bootstrapProject({id:config.project.id,name:config.project.name,tokenHash:hash(this.token)});config.stores.putAgent({id:config.agent.id,projectId:config.project.id,name:config.agent.name,enabled:config.agent.enabled??true});for(const tool of config.tools??[])this.registerTool(tool);for(const policy of config.policies??[])this.addPolicy(policy);}
  get bootstrapToken(){const value=this.bootstrap;this.bootstrap=undefined;return value;}
  get url(){const address=this.server.address() as AddressInfo|null;return address?`http://${this.bind}:${address.port}`:undefined;}
  async start(){await new Promise<void>((resolve,reject)=>{this.server.once('error',reject);this.server.listen(this.requestedPort,this.bind,()=>{this.server.off('error',reject);resolve();});});return{url:this.url};}
  async stop(){if(this.server.listening)await new Promise<void>((resolve,reject)=>this.server.close(e=>e?reject(e):resolve()));}
  registerTool(tool:ToolConfig){this.config.stores.putTool({id:tool.id??randomUUID(),projectId:this.config.project.id,key:tool.key,name:tool.name,method:tool.method.toUpperCase(),url:tool.url,inputSchema:tool.inputSchema??null,outputSchema:tool.outputSchema??null,credentialRef:tool.credentialRef??null,credentialHeader:tool.credentialHeader??null,timeoutMs:tool.timeoutMs??30000,responseMaxBytes:tool.responseMaxBytes??1048576,enabled:tool.enabled??true,tags:tool.tags??[],networkPolicy:{allowLoopback:tool.networkPolicy?.allowLoopback??false,allowPrivateRanges:tool.networkPolicy?.allowPrivateRanges??false}});}
  registerExecutor(toolKey:string,executor:LocalToolExecutor){(this.config.executors??={})[toolKey]=executor;}
  executeTool(toolKey:string,input:JsonValue,idempotencyKey?:string){return this.execute(toolKey,input,idempotencyKey);}
  decideApproval(id:string,approve:boolean){return this.resolveApproval(id,approve);}
  addPolicy(policy:PolicyConfig){this.config.stores.putPolicy({id:policy.id??randomUUID(),projectId:this.config.project.id,name:policy.name,enabled:policy.enabled??true,priority:policy.priority??0,decision:policy.decision,toolKey:policy.toolKey??null,agentId:policy.agentId??null,method:policy.method??null,requiredTags:policy.requiredTags??[],createdAt:policy.createdAt??this.clock.now().toISOString()});}
  private authenticated(req:IncomingMessage){const value=req.headers.authorization;if(typeof value!=='string'||!value.startsWith('Bearer '))return false;const supplied=Buffer.from(hash(value.slice(7)),'hex'),expected=Buffer.from(this.config.stores.project(this.config.project.id)?.tokenHash??'','hex');return supplied.length===expected.length&&expected.length===32&&timingSafeEqual(supplied,expected);}
  private send(res:ServerResponse,status:number,body:JsonValue,requestId:string){res.writeHead(status,{'content-type':'application/json','x-request-id':requestId,'cache-control':'no-store'});res.end(JSON.stringify(body));}
  private error(res:ServerResponse,status:number,code:string,requestId:string,details?:Record<string,JsonValue>){this.send(res,status,{error:{code,requestId,...(details??{})}},requestId);}
  private async body(req:IncomingMessage){if(!String(req.headers['content-type']??'').toLowerCase().startsWith('application/json'))throw new GatewayError('VALIDATION_ERROR',415);const chunks:Buffer[]=[];let size=0;for await(const chunk of req){size+=chunk.length;if(size>1048576)throw new GatewayError('VALIDATION_ERROR',413);chunks.push(chunk);}try{return JSON.parse(Buffer.concat(chunks).toString('utf8')||'{}') as any;}catch{throw new GatewayError('VALIDATION_ERROR',400);}}
  private async handle(req:IncomingMessage,res:ServerResponse){const requestId=typeof req.headers['x-request-id']==='string'&&req.headers['x-request-id'].length<128?req.headers['x-request-id']:randomUUID();try{const origin=req.headers.origin;if(origin&&!(this.config.allowedOrigins??[]).includes(origin))return this.error(res,403,'ORIGIN_REJECTED',requestId);if(!this.authenticated(req))return this.error(res,401,'AUTHENTICATION_FAILED',requestId);const url=new URL(req.url??'/','http://local');this.config.logger?.({event:'local.request',requestId,projectId:this.config.project.id,method:req.method,path:url.pathname});if(req.method==='GET'&&url.pathname==='/v1/agent/me')return this.send(res,200,{organizationId:this.config.project.id,agentId:this.config.agent.id,agentName:this.config.agent.name,environment:'local'},requestId);if(req.method==='GET'&&url.pathname==='/v1/agent/tools')return this.send(res,200,this.config.stores.tools(this.config.project.id).filter(x=>x.enabled).map(x=>({toolKey:x.key,name:x.name,description:null,inputSchema:x.inputSchema})),requestId);
      let m=url.pathname.match(/^\/v1\/agent\/tools\/([^/]+)\/(execute|dry-run)$/);if(req.method==='POST'&&m){const input=await this.body(req);const toolKey=decodeURIComponent(m[1]);if(m[2]==='dry-run')return this.send(res,200,this.dryRun(toolKey,asJson(input.input??{})),requestId);const key=typeof req.headers['idempotency-key']==='string'?req.headers['idempotency-key']:undefined;const result=await this.execute(toolKey,asJson(input.input??{}),key);return this.send(res,result.status,result.body,requestId);}
      m=url.pathname.match(/^\/v1\/agent\/runs\/([^/]+)(\/events|\/receipt)?$/);if(req.method==='GET'&&m){const runId=decodeURIComponent(m[1]);if(m[2]==='/events')return this.send(res,200,this.config.stores.events(runId),requestId);if(m[2]==='/receipt'){const receipt=this.config.stores.receipt(runId);return receipt?this.send(res,200,receipt,requestId):this.error(res,404,'NOT_FOUND',requestId);}const run=this.config.stores.run(runId);if(!run)return this.error(res,404,'NOT_FOUND',requestId);const receipt=this.config.stores.receipt(runId)??null;return this.send(res,200,{runId:run.id,status:run.status,startedAt:run.startedAt,finishedAt:run.finishedAt,eventCount:this.config.stores.events(runId).length,finalChainHash:run.finalChainHash,receipt},requestId);}
      m=url.pathname.match(/^\/v1\/(?:agent|local)\/approvals(?:\/([^/]+)(?:\/(approve|reject))?)?$/);if(m){if(req.method==='GET'){if(!m[1])return this.send(res,200,this.config.stores.approvals(this.config.project.id).map(a=>this.approvalView(a)),requestId);const approval=this.config.stores.approval(decodeURIComponent(m[1]));return approval?this.send(res,200,this.approvalView(approval),requestId):this.error(res,404,'NOT_FOUND',requestId);}if(req.method==='POST'&&m[1]&&m[2]){const result=await this.resolveApproval(decodeURIComponent(m[1]),m[2]==='approve');return this.send(res,result.status,result.body,requestId);}}
      return this.error(res,404,'NOT_FOUND',requestId);
    }catch(error){const safe=error instanceof GatewayError?error:new GatewayError('SERVER_ERROR',500);return this.error(res,safe.status,safe.code,requestId);}}
  private context(tool:StoredTool,runId:string,input:JsonValue):AuthorizationContext{return{tenantId:this.config.project.id,agentId:this.config.agent.id,runId,toolKey:tool.key,method:tool.method,url:tool.url,tags:tool.tags,input};}
  private policy(tool:StoredTool,runId:string,input:JsonValue){const context=this.context(tool,runId,input);const result=evaluatePolicy({subject:{agentId:this.config.agent.id,tags:tool.tags},tool:{key:tool.key,method:tool.method},input,policies:this.config.stores.policies(this.config.project.id),defaultDecision:'DENY'});return{context,result};}
  private dryRun(toolKey:string,input:JsonValue):JsonValue{const tool=this.config.stores.tool(this.config.project.id,toolKey);if(!tool||!tool.enabled)throw new GatewayError('NOT_FOUND',404);const validation=validateToolInput(tool.inputSchema,input);if(!validation.valid)throw new GatewayError('TOOL_INPUT_INVALID',400);const {result}=this.policy(tool,'simulation',input);return{mode:'DRY_RUN',predictedDecision:result.decision,executable:result.decision==='ALLOW',wouldRequireApproval:result.decision==='REQUIRE_APPROVAL',wouldRequireGrant:false,credentialsAccessed:false,downstreamExecuted:false,approvalRequired:result.decision==='REQUIRE_APPROVAL',predictedFinalState:result.decision==='ALLOW'?'EXECUTABLE':result.decision==='DENY'?'BLOCKED':'WAITING_FOR_APPROVAL',tool:{toolKey:tool.key,name:tool.name,method:tool.method},agent:{id:this.config.agent.id,name:this.config.agent.name},checks:{inputValidation:'PASS',policy:result.decision,credentialAccess:'NOT_PERFORMED',downstreamExecution:'NOT_PERFORMED'},grantEvaluation:{allowed:true},risk:{score:0,level:'LOW',riskModelVersion:'v1',factors:[]},policySimulation:{decision:result.decision,reason:result.reason,...(result.matchedPolicy?{policyId:result.matchedPolicy.id,policyName:result.matchedPolicy.name}:{})}};}
  private execute(toolKey:string,input:JsonValue,idempotencyKey?:string){const mapKey=idempotencyKey?`${this.config.project.id}:${idempotencyKey}`:undefined;if(mapKey&&this.inflight.has(mapKey))return this.inflight.get(mapKey)!;const work=this.executeOnce(toolKey,input,idempotencyKey).then((result)=>{if(idempotencyKey){const value=result.body as any,runId=value?.runId??value?.error?.runId;if(typeof runId==='string')this.config.stores.completeIdempotency(this.config.project.id,idempotencyKey,result.body,runId);}return result;});if(mapKey){this.inflight.set(mapKey,work);void work.finally(()=>this.inflight.delete(mapKey));}return work;}
  private async executeOnce(toolKey:string,input:JsonValue,idempotencyKey?:string):Promise<{status:number;body:JsonValue}>{const tool=this.config.stores.tool(this.config.project.id,toolKey);if(!tool||!tool.enabled)return{status:404,body:{error:{code:'NOT_FOUND'}}};const validation=validateToolInput(tool.inputSchema,input);if(!validation.valid)return{status:400,body:{error:{code:'TOOL_INPUT_INVALID'}}};const fingerprint=executionRequestFingerprint({toolKey,payload:input});if(idempotencyKey){const claim=this.config.stores.claimIdempotency(this.config.project.id,idempotencyKey,fingerprint);if(claim==='CONFLICT')return{status:409,body:{error:{code:'IDEMPOTENCY_CONFLICT'}}};if(claim==='IN_PROGRESS')return{status:409,body:{error:{code:'IDEMPOTENCY_IN_PROGRESS'}}};if(claim==='COMPLETE')return{status:200,body:this.config.stores.idempotency(this.config.project.id,idempotencyKey)?.response??{error:{code:'SERVER_ERROR'}}};}
    const runId=randomUUID(),startedAt=this.clock.now().toISOString();this.config.stores.createRun({id:runId,projectId:this.config.project.id,agentId:this.config.agent.id,toolKey,status:'RUNNING',startedAt,finishedAt:null,finalChainHash:AUDIT_CHAIN_GENESIS,resultJson:null});this.append(runId,'RUN_STARTED',{projectId:this.config.project.id,agentId:this.config.agent.id});this.append(runId,'TOOL_REQUESTED',{toolKey,payloadDigest:hash(canonicalJsonStringify(input))});const {context,result}=this.policy(tool,runId,input);this.append(runId,'POLICY_EVALUATED',{decision:result.decision,policyId:result.matchedPolicy?.id??null});
    if(result.decision==='DENY'){const receipt=this.finish(runId,{decision:'DENY'});return{status:403,body:{error:{code:'POLICY_DENIED',runId},receipt}};}
    if(result.decision==='REQUIRE_APPROVAL'){const id=randomUUID(),expiresAt=new Date(this.clock.now().getTime()+1800000).toISOString();this.config.stores.putApproval({id,projectId:this.config.project.id,runId,agentId:this.config.agent.id,toolKey,policyId:result.matchedPolicy?.id??null,contextHash:approvalContextHash(context,result.matchedPolicy?.id),status:'PENDING',input,expiresAt,decidedAt:null});this.append(runId,'APPROVAL_REQUESTED',{approvalRequestId:id,expiresAt});return{status:403,body:{error:{code:'APPROVAL_REQUIRED',approvalRequestId:id,runId}}};}
    return this.perform(tool,runId,input);}
  private async perform(tool:StoredTool,runId:string,input:JsonValue):Promise<{status:number;body:JsonValue}>{let secret:string|undefined;try{const headers:Record<string,string>={'content-type':'application/json'};if(tool.credentialRef){secret=await this.config.credentials.resolve(tool.credentialRef);if(!secret)throw new GatewayError('TOOL_CREDENTIAL_UNAVAILABLE',503);headers[tool.credentialHeader??'authorization']=(tool.credentialHeader??'authorization').toLowerCase()==='authorization'?`Bearer ${secret}`:secret;this.append(runId,'TOOL_CREDENTIAL_ACCESSED',{credentialRef:tool.credentialRef});}const executor=this.config.executors?.[tool.key];if(executor){const output=redact(await executor({toolKey:tool.key,input,credential:secret}),secret);this.append(runId,'TOOL_EXECUTED',{status:200,responseDigest:hash(canonicalJsonStringify(output)),ok:true});const receipt=this.finish(runId,output);return{status:200,body:{ok:true,toolKey:tool.key,runId,receipt,http:{status:200,durationMs:0},output}};}const response=await safeHttpFetch(tool.url,{method:tool.method,headers,body:['GET','HEAD'].includes(tool.method)?undefined:JSON.stringify(input)},{networkPolicy:tool.networkPolicy,timeoutMs:tool.timeoutMs,responseMaxBytes:tool.responseMaxBytes});let text=response.text;if(secret)text=text.split(secret).join('[REDACTED]');let output:JsonValue;try{output=asJson(JSON.parse(text));}catch{output={text};}this.append(runId,'TOOL_EXECUTED',{status:response.status,responseDigest:hash(text),ok:response.ok});const receipt=this.finish(runId,output);return{status:response.ok?200:502,body:response.ok?{ok:true,toolKey:tool.key,runId,receipt,http:{status:response.status,durationMs:0},output}:{error:{code:'DOWNSTREAM_FAILED',runId}}};}catch(error){const code=error instanceof GatewayError?error.code:'DOWNSTREAM_FAILED';this.append(runId,'ERROR',{code});this.finish(runId,{error:code});return{status:error instanceof GatewayError?error.status:502,body:{error:{code,runId}}};}finally{secret=undefined;}}
  private append(runId:string,type:AuditEventType,data?:JsonValue){return this.config.stores.transaction(()=>{const prior=this.config.stores.events(runId),seq=prior.length+1,prevChainHash=prior.at(-1)?.chainHash??AUDIT_CHAIN_GENESIS,event:AuditEvent={id:randomUUID(),runId,seq,type,at:this.clock.now().toISOString(),data};event.eventHash=computeAuditEventHash(event);event.prevChainHash=prevChainHash;event.chainHash=computeAuditChainHash(prevChainHash,event.eventHash);this.config.stores.appendEvent(event);return event;});}
  private finish(runId:string,result:JsonValue){return this.config.stores.transaction(()=>{const event=this.append(runId,'RUN_FINISHED',{resultDigest:hash(canonicalJsonStringify(result))}),finishedAt=this.clock.now().toISOString(),events=this.config.stores.events(runId),receipt={runId,eventCount:events.length,finalChainHash:event.chainHash!,issuedAt:finishedAt};this.config.stores.updateRun(runId,{status:'FINISHED',finishedAt,finalChainHash:event.chainHash!,resultJson:result});this.config.stores.putReceipt(receipt);return receipt;});}
  private approvalView(a:StoredApproval):JsonValue{const run=this.config.stores.run(a.runId)!;return{approvalRequestId:a.id,runId:a.runId,status:a.status,expiresAt:a.expiresAt,decidedAt:a.decidedAt,run:{status:run.status,finishedAt:run.finishedAt,receipt:this.config.stores.receipt(run.id)??null}};}
  private async resolveApproval(id:string,approve:boolean):Promise<{status:number;body:JsonValue}>{const approval=this.config.stores.approval(id);if(!approval)return{status:404,body:{error:{code:'NOT_FOUND'}}};const tool=this.config.stores.tool(this.config.project.id,approval.toolKey);if(!tool)return{status:404,body:{error:{code:'NOT_FOUND'}}};const context=this.context(tool,approval.runId,approval.input);if(!matchesApprovalContext({...approval,tenantId:approval.projectId},context,approval.policyId??undefined))return{status:409,body:{error:{code:'APPROVAL_INVALID'}}};const now=this.clock.now();if(new Date(approval.expiresAt)<=now){if(canTransition(approval.status,'EXPIRED'))this.config.stores.transitionApproval(id,approval.status,'EXPIRED',new Date(approval.expiresAt).toISOString());this.append(approval.runId,'APPROVAL_EXPIRED',{approvalRequestId:id});const receipt=this.finish(approval.runId,{decision:'EXPIRED'});return{status:409,body:{error:{code:'APPROVAL_EXPIRED'},receipt}};}if(!approve){if(!this.config.stores.transitionApproval(id,'PENDING','REJECTED',now.toISOString()))return{status:409,body:{error:{code:'APPROVAL_INVALID'}}};this.append(approval.runId,'APPROVAL_REJECTED',{approvalRequestId:id});const receipt=this.finish(approval.runId,{decision:'REJECTED'});return{status:200,body:Object.assign({},this.approvalView(this.config.stores.approval(id)!) as object,{receipt}) as JsonValue};}if(!this.config.stores.transitionApproval(id,'PENDING','APPROVED',now.toISOString()))return{status:200,body:this.approvalView(this.config.stores.approval(id)!)};this.append(approval.runId,'APPROVAL_APPROVED',{approvalRequestId:id});if(!this.config.stores.transitionApproval(id,'APPROVED','CONSUMED',now.toISOString()))return{status:409,body:{error:{code:'APPROVAL_INVALID'}}};this.append(approval.runId,'APPROVAL_CONSUMED',{approvalRequestId:id});return this.perform(tool,approval.runId,approval.input);}
}
