import { lookup as dnsLookup } from 'node:dns/promises';
import { isIP } from 'node:net';
import { Agent } from 'undici';
export type NetworkPolicy={allowLoopback?:boolean;allowPrivateRanges?:boolean};
export class GatewayError extends Error{constructor(readonly code:string,readonly status:number){super(code);this.name='GatewayError';}}
export function isLoopbackAddress(address:string){const n=address.toLowerCase().split('%')[0],mapped=n.startsWith('::ffff:')?n.slice(7):n;return n==='::1'||mapped.startsWith('127.');}
export function isPrivateAddress(address:string){const n=address.toLowerCase().split('%')[0];if(n==='::1'||n==='::'||n.startsWith('fc')||n.startsWith('fd')||/^(fe8|fe9|fea|feb)/.test(n))return true;const p=(n.startsWith('::ffff:')?n.slice(7):n).split('.').map(Number);if(p.length!==4||p.some(x=>!Number.isInteger(x)||x<0||x>255))return false;const[a,b]=p;return a===0||a===10||a===127||(a===100&&b>=64&&b<=127)||(a===169&&b===254)||(a===172&&b>=16&&b<=31)||(a===192&&b===168)||a>=224;}
async function validate(raw:string,policy:NetworkPolicy){let url:URL;try{url=new URL(raw);}catch{throw new GatewayError('EGRESS_DESTINATION_BLOCKED',403);}if(!['http:','https:'].includes(url.protocol)||url.username||url.password)throw new GatewayError('EGRESS_DESTINATION_BLOCKED',403);const host=url.hostname.toLowerCase(),addresses=isIP(host)?[{address:host,family:isIP(host)}]:await dnsLookup(host,{all:true,verbatim:true}).catch(()=>[]);if(!addresses.length)throw new GatewayError('EGRESS_DESTINATION_BLOCKED',403);for(const {address} of addresses){if(isLoopbackAddress(address)){if(!policy.allowLoopback)throw new GatewayError('EGRESS_DESTINATION_BLOCKED',403);}else if(isPrivateAddress(address)&&!policy.allowPrivateRanges)throw new GatewayError('EGRESS_DESTINATION_BLOCKED',403);}return{url,addresses};}
async function limited(response:Response,limit:number){const declared=response.headers.get('content-length');if(declared&&/^\d+$/.test(declared)&&Number(declared)>limit)throw new GatewayError('DOWNSTREAM_RESPONSE_TOO_LARGE',502);if(!response.body)return response.text();const reader=response.body.getReader(),chunks:Uint8Array[]=[];let size=0;try{for(;;){const{done,value}=await reader.read();if(done)break;size+=value.byteLength;if(size>limit){await reader.cancel();throw new GatewayError('DOWNSTREAM_RESPONSE_TOO_LARGE',502);}chunks.push(value);}}finally{reader.releaseLock();}const all=new Uint8Array(size);let offset=0;for(const chunk of chunks){all.set(chunk,offset);offset+=chunk.length;}return new TextDecoder().decode(all);}
export async function safeHttpFetch(raw:string,init:RequestInit,options:{networkPolicy?:NetworkPolicy;timeoutMs:number;responseMaxBytes:number}){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),options.timeoutMs);try{let current=new URL(raw);for(let redirects=0;redirects<=3;redirects++){const checked=await validate(current.toString(),options.networkPolicy??{}),pinned=checked.addresses,dispatcher=new Agent({connect:{lookup(_host,opts,cb){const family=typeof opts==='object'?opts.family:0,candidates=family?pinned.filter(x=>x.family===family):pinned;if(!candidates.length)return cb(new Error('No validated address'),' ',0);if(typeof opts==='object'&&opts.all)return cb(null,candidates as never);return cb(null,candidates[0].address,candidates[0].family);}}});try{const response=await fetch(checked.url,{...init,redirect:'manual',signal:controller.signal,dispatcher} as RequestInit&{dispatcher:Agent});if([301,302,303,307,308].includes(response.status)){await response.body?.cancel();const location=response.headers.get('location');if(!location||redirects===3)throw new GatewayError('EGRESS_REDIRECT_BLOCKED',403);current=new URL(location,checked.url);continue;}return{ok:response.ok,status:response.status,headers:response.headers,text:await limited(response,options.responseMaxBytes)};}finally{await dispatcher.close();}}throw new GatewayError('EGRESS_REDIRECT_BLOCKED',403);}catch(error){if(controller.signal.aborted)throw new GatewayError('DOWNSTREAM_TIMEOUT',504);if(error instanceof GatewayError)throw error;throw new GatewayError('DOWNSTREAM_NETWORK_ERROR',502);}finally{clearTimeout(timer);}}
