import { readFileSync, writeFileSync, mkdirSync, cpSync, realpathSync } from 'node:fs';
import { join, dirname, sep } from 'node:path';
import { fileURLToPath } from 'node:url';
import { execute } from './protected-flow.mjs';
const repo=dirname(dirname(fileURLToPath(import.meta.url)));
const report=JSON.parse(readFileSync(join(repo,'certification/clean-room.json'),'utf8'));
const app=join(report.root,'app');
// Both sides must be canonical: macOS temporary roots can traverse an OS alias.
const canonicalApp=realpathSync(app);
for(const name of ['protocol','core','verifier','gateway','storage-sqlite','mcp','cli'])if(!realpathSync(join(app,'node_modules/@agentactionverifier',name)).startsWith(canonicalApp+sep))throw Error('Resolution escapes packed clean room');
let test=readFileSync(join(repo,'packages/mcp/test/mcp-e2e.test.mjs'),'utf8').replace("'../dist/index.js'","'@agentactionverifier/mcp'");
test=test.replace("secret='mcp-secret-never-leak'","secret='AAV_RELEASE_CANARY_'+(await import('node:crypto')).randomBytes(24).toString('hex'),counter=join(dir,'upstream-count.txt'),count=()=>{try{return readFileSync(counter,'utf8').split(String.fromCharCode(10)).filter(Boolean).length;}catch{return 0;}}");
test=test.replaceAll('args:[fixture]',"args:[fixture,'--count-file',counter]");
test=test.replace("assert.equal(allowed.isError,undefined);","assert.equal(count(),1);assert.equal(allowed.isError,undefined);");
test=test.replace("const denied=await client.callTool", "assert.equal(count(),2);const denied=await client.callTool");
test=test.replace("const pending=await client.callTool", "assert.equal(count(),2);const pending=await client.callTool");
test=test.replace("const approvals=await Promise.all(Array.from({length:10}","assert.equal(count(),2);const approvals=await Promise.all(Array.from({length:8}");
test=test.replace("const approvalReceipt=db.receipt", "assert.equal(count(),3);const approvalReceipt=db.receipt");
test=test.replace("const changed=await client.callTool", "assert.equal(count(),3);const changed=await client.callTool");
test=test.replace("const expired=await client.callTool", "assert.equal(count(),3);const expired=await client.callTool");
test=test.replace("assert.equal(readFileSync(dbPath)", "assert.equal(count(),3);for(const f of (await import('node:fs')).readdirSync(dir))assert.equal(readFileSync(join(dir,f)).includes(Buffer.from(secret)),false,'canary leaked to local database/WAL/counter artifacts');assert.equal(readFileSync(dbPath)");
let fixture=readFileSync(join(repo,'packages/mcp/test/fixtures/upstream.mjs'),'utf8');
fixture="import { appendFileSync } from 'node:fs';\n"+fixture;
fixture=fixture.replace('calls++;const secret=',"calls++;const ci=process.argv.indexOf('--count-file');if(ci>=0)appendFileSync(process.argv[ci+1],String.fromCharCode(49,10));const secret=");
mkdirSync(join(app,'fixtures'),{recursive:true});writeFileSync(join(app,'packed-mcp.test.mjs'),test);writeFileSync(join(app,'fixtures/upstream.mjs'),fixture);
let sqlite=readFileSync(join(repo,'packages/storage-sqlite/test/storage.test.mjs'),'utf8').replace("'../dist/index.js'","'@agentactionverifier/storage-sqlite'");
sqlite += "\ntest('persisted v1 upgrade preserves project, agent, run, audit and receipt',async()=>{const v=JSON.parse((await import('node:fs')).readFileSync('audit-vector.json','utf8')),path=join(mkdtempSync(join(tmpdir(),'aav-release-v1-')),'aav.db'),old=new SQLiteStorage(path);old.bootstrapProject({id:'persist',name:'Preserved',tokenHash:'synthetic'});old.putAgent({id:'persist-agent',projectId:'persist',name:'Preserved agent',enabled:true});old.createRun({id:v.receipt.runId,projectId:'persist',agentId:'persist-agent',toolKey:'fixture',status:'COMPLETED',startedAt:v.events[0].at,finishedAt:v.receipt.issuedAt,finalChainHash:v.receipt.finalChainHash,resultJson:null});for(const e of v.events)old.appendEvent(e);old.putReceipt(v.receipt);old.db.exec('DROP TABLE mcp_tool_mappings;DROP TABLE mcp_upstreams;UPDATE schema_meta SET version=1;');old.close();const db=new SQLiteStorage(path);assert.equal(db.project('persist').name,'Preserved');assert.equal(db.agent('persist-agent').enabled,true);assert.ok(db.run(v.receipt.runId));assert.deepEqual((await import('@agentactionverifier/verifier')).verifyReceipt(db.receipt(v.receipt.runId),db.events(v.receipt.runId)),{ok:true});assert.equal(db.db.prepare('SELECT version FROM schema_meta').get().version,2);db.close();});\n";
writeFileSync(join(app,'packed-storage.test.mjs'),sqlite);
const env=Object.fromEntries(Object.entries(process.env).filter(([key])=>/^(PATH|HOME|USERPROFILE|SYSTEMROOT|WINDIR|TEMP|TMP|PATHEXT|COMSPEC)$/i.test(key)));
const vector=JSON.parse(readFileSync(join(repo,'packages/protocol/fixtures/audit-chain-v1.json'),'utf8'));
writeFileSync(join(app,'audit-vector.json'),JSON.stringify(vector));
const result=await execute(process.execPath,['--test','packed-mcp.test.mjs','packed-storage.test.mjs'],{cwd:app,env});
const verified=await execute(process.execPath,['--input-type=module','-e',"import {verifyReceipt} from '@agentactionverifier/verifier';import{readFileSync}from'node:fs';const v=JSON.parse(readFileSync('audit-vector.json'));if(!verifyReceipt(v.receipt,v.events).ok)throw Error('v1 compatibility');console.log('v1 PASS');"],{cwd:app,env});
writeFileSync(join(repo,'certification/packed-e2e.json'),JSON.stringify({ok:true,tarballsOnly:true,realMcpClient:true,upstreamTransport:'stdio',frontTransport:'in-memory; separate CLI clean-room confirms real stdio front transport',tests:6,allowUpstreamCalls:1,denyUpstreamCalls:0,beforeApprovalCalls:0,approvedUpstreamCalls:1,rejectUpstreamCalls:0,expiredUpstreamCalls:0,argumentTamperUpstreamCalls:0,approvalRaceRequests:8,approvalRaceUpstreamCalls:1,idempotencyRequests:10,idempotencyUpstreamCalls:1,uniqueCanary:true,plaintextCanaryFindings:0,sqliteMigration:true,migrationAuditPersistence:true,auditV1Compatibility:true,receiptVerify:true,tamper:true,cloudEnvironmentRequired:false,testOutput:result.stdout},null,2)+'\n');
console.log('Packed MCP, migration and compatible audit vectors PASS');
